# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ActivityEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActivityEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActivityEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ActivityEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x45\x56", size_prefixed=size_prefixed)

    # ActivityEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActivityEvent
    def Activity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ActivityEvent
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ActivityEvent
    def Total(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def ActivityEventStart(builder):
    builder.StartObject(3)

def Start(builder):
    ActivityEventStart(builder)

def ActivityEventAddActivity(builder, activity):
    builder.PrependInt8Slot(0, activity, 0)

def AddActivity(builder, activity):
    ActivityEventAddActivity(builder, activity)

def ActivityEventAddStep(builder, step):
    builder.PrependUint16Slot(1, step, 0)

def AddStep(builder, step):
    ActivityEventAddStep(builder, step)

def ActivityEventAddTotal(builder, total):
    builder.PrependUint16Slot(2, total, 0)

def AddTotal(builder, total):
    ActivityEventAddTotal(builder, total)

def ActivityEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ActivityEventEnd(builder)
