# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ApplyUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ApplyUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsApplyUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ApplyUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ApplyUpdateStart(builder):
    builder.StartObject(0)

def Start(builder):
    ApplyUpdateStart(builder)

def ApplyUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return ApplyUpdateEnd(builder)
