# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArmTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArmTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArmTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ArmTelemetryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # ArmTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArmTelemetry
    def TargetPosition(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TargetPositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TargetPositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TargetPositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ArmTelemetry
    def TargetVelocity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TargetVelocityAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TargetVelocityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TargetVelocityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ArmTelemetry
    def TargetTorque(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TargetTorqueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TargetTorqueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TargetTorqueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ArmTelemetry
    def ActualPosition(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def ActualPositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def ActualPositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def ActualPositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ArmTelemetry
    def ActualVelocity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def ActualVelocityAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def ActualVelocityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def ActualVelocityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ArmTelemetry
    def ActualTorque(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def ActualTorqueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def ActualTorqueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def ActualTorqueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ArmTelemetry
    def MotorTemperature(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def MotorTemperatureAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def MotorTemperatureLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def MotorTemperatureIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ArmTelemetry
    def DriverTemperature(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def DriverTemperatureAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def DriverTemperatureLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def DriverTemperatureIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ArmTelemetry
    def FaultCodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ArmTelemetry
    def FaultCodesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ArmTelemetry
    def FaultCodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def FaultCodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # ArmTelemetry
    def Faulted(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ArmTelemetry
    def FaultedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # ArmTelemetry
    def FaultedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def FaultedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # ArmTelemetry
    def QuickStopActive(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ArmTelemetry
    def QuickStopActiveAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # ArmTelemetry
    def QuickStopActiveLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def QuickStopActiveIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # ArmTelemetry
    def TcpActualPosition(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpActualPositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpActualPositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpActualPositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # ArmTelemetry
    def TcpActualOrientation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpActualOrientationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpActualOrientationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpActualOrientationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # ArmTelemetry
    def TcpActualLinearVel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpActualLinearVelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpActualLinearVelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpActualLinearVelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # ArmTelemetry
    def TcpActualAngularVel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpActualAngularVelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpActualAngularVelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpActualAngularVelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # ArmTelemetry
    def TcpCommandedPosition(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpCommandedPositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpCommandedPositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpCommandedPositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # ArmTelemetry
    def TcpCommandedOrientation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpCommandedOrientationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpCommandedOrientationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpCommandedOrientationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # ArmTelemetry
    def TcpCommandedLinearVel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpCommandedLinearVelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpCommandedLinearVelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpCommandedLinearVelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

    # ArmTelemetry
    def TcpCommandedAngularVel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ArmTelemetry
    def TcpCommandedAngularVelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ArmTelemetry
    def TcpCommandedAngularVelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArmTelemetry
    def TcpCommandedAngularVelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

def ArmTelemetryStart(builder):
    builder.StartObject(19)

def Start(builder):
    ArmTelemetryStart(builder)

def ArmTelemetryAddTargetPosition(builder, targetPosition):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(targetPosition), 0)

def AddTargetPosition(builder, targetPosition):
    ArmTelemetryAddTargetPosition(builder, targetPosition)

def ArmTelemetryStartTargetPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTargetPositionVector(builder, numElems):
    return ArmTelemetryStartTargetPositionVector(builder, numElems)

def ArmTelemetryAddTargetVelocity(builder, targetVelocity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(targetVelocity), 0)

def AddTargetVelocity(builder, targetVelocity):
    ArmTelemetryAddTargetVelocity(builder, targetVelocity)

def ArmTelemetryStartTargetVelocityVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTargetVelocityVector(builder, numElems):
    return ArmTelemetryStartTargetVelocityVector(builder, numElems)

def ArmTelemetryAddTargetTorque(builder, targetTorque):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(targetTorque), 0)

def AddTargetTorque(builder, targetTorque):
    ArmTelemetryAddTargetTorque(builder, targetTorque)

def ArmTelemetryStartTargetTorqueVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTargetTorqueVector(builder, numElems):
    return ArmTelemetryStartTargetTorqueVector(builder, numElems)

def ArmTelemetryAddActualPosition(builder, actualPosition):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(actualPosition), 0)

def AddActualPosition(builder, actualPosition):
    ArmTelemetryAddActualPosition(builder, actualPosition)

def ArmTelemetryStartActualPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActualPositionVector(builder, numElems):
    return ArmTelemetryStartActualPositionVector(builder, numElems)

def ArmTelemetryAddActualVelocity(builder, actualVelocity):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(actualVelocity), 0)

def AddActualVelocity(builder, actualVelocity):
    ArmTelemetryAddActualVelocity(builder, actualVelocity)

def ArmTelemetryStartActualVelocityVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActualVelocityVector(builder, numElems):
    return ArmTelemetryStartActualVelocityVector(builder, numElems)

def ArmTelemetryAddActualTorque(builder, actualTorque):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(actualTorque), 0)

def AddActualTorque(builder, actualTorque):
    ArmTelemetryAddActualTorque(builder, actualTorque)

def ArmTelemetryStartActualTorqueVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActualTorqueVector(builder, numElems):
    return ArmTelemetryStartActualTorqueVector(builder, numElems)

def ArmTelemetryAddMotorTemperature(builder, motorTemperature):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(motorTemperature), 0)

def AddMotorTemperature(builder, motorTemperature):
    ArmTelemetryAddMotorTemperature(builder, motorTemperature)

def ArmTelemetryStartMotorTemperatureVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMotorTemperatureVector(builder, numElems):
    return ArmTelemetryStartMotorTemperatureVector(builder, numElems)

def ArmTelemetryAddDriverTemperature(builder, driverTemperature):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(driverTemperature), 0)

def AddDriverTemperature(builder, driverTemperature):
    ArmTelemetryAddDriverTemperature(builder, driverTemperature)

def ArmTelemetryStartDriverTemperatureVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDriverTemperatureVector(builder, numElems):
    return ArmTelemetryStartDriverTemperatureVector(builder, numElems)

def ArmTelemetryAddFaultCodes(builder, faultCodes):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(faultCodes), 0)

def AddFaultCodes(builder, faultCodes):
    ArmTelemetryAddFaultCodes(builder, faultCodes)

def ArmTelemetryStartFaultCodesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartFaultCodesVector(builder, numElems):
    return ArmTelemetryStartFaultCodesVector(builder, numElems)

def ArmTelemetryAddFaulted(builder, faulted):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(faulted), 0)

def AddFaulted(builder, faulted):
    ArmTelemetryAddFaulted(builder, faulted)

def ArmTelemetryStartFaultedVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartFaultedVector(builder, numElems):
    return ArmTelemetryStartFaultedVector(builder, numElems)

def ArmTelemetryAddQuickStopActive(builder, quickStopActive):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(quickStopActive), 0)

def AddQuickStopActive(builder, quickStopActive):
    ArmTelemetryAddQuickStopActive(builder, quickStopActive)

def ArmTelemetryStartQuickStopActiveVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartQuickStopActiveVector(builder, numElems):
    return ArmTelemetryStartQuickStopActiveVector(builder, numElems)

def ArmTelemetryAddTcpActualPosition(builder, tcpActualPosition):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(tcpActualPosition), 0)

def AddTcpActualPosition(builder, tcpActualPosition):
    ArmTelemetryAddTcpActualPosition(builder, tcpActualPosition)

def ArmTelemetryStartTcpActualPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpActualPositionVector(builder, numElems):
    return ArmTelemetryStartTcpActualPositionVector(builder, numElems)

def ArmTelemetryAddTcpActualOrientation(builder, tcpActualOrientation):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(tcpActualOrientation), 0)

def AddTcpActualOrientation(builder, tcpActualOrientation):
    ArmTelemetryAddTcpActualOrientation(builder, tcpActualOrientation)

def ArmTelemetryStartTcpActualOrientationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpActualOrientationVector(builder, numElems):
    return ArmTelemetryStartTcpActualOrientationVector(builder, numElems)

def ArmTelemetryAddTcpActualLinearVel(builder, tcpActualLinearVel):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(tcpActualLinearVel), 0)

def AddTcpActualLinearVel(builder, tcpActualLinearVel):
    ArmTelemetryAddTcpActualLinearVel(builder, tcpActualLinearVel)

def ArmTelemetryStartTcpActualLinearVelVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpActualLinearVelVector(builder, numElems):
    return ArmTelemetryStartTcpActualLinearVelVector(builder, numElems)

def ArmTelemetryAddTcpActualAngularVel(builder, tcpActualAngularVel):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(tcpActualAngularVel), 0)

def AddTcpActualAngularVel(builder, tcpActualAngularVel):
    ArmTelemetryAddTcpActualAngularVel(builder, tcpActualAngularVel)

def ArmTelemetryStartTcpActualAngularVelVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpActualAngularVelVector(builder, numElems):
    return ArmTelemetryStartTcpActualAngularVelVector(builder, numElems)

def ArmTelemetryAddTcpCommandedPosition(builder, tcpCommandedPosition):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(tcpCommandedPosition), 0)

def AddTcpCommandedPosition(builder, tcpCommandedPosition):
    ArmTelemetryAddTcpCommandedPosition(builder, tcpCommandedPosition)

def ArmTelemetryStartTcpCommandedPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpCommandedPositionVector(builder, numElems):
    return ArmTelemetryStartTcpCommandedPositionVector(builder, numElems)

def ArmTelemetryAddTcpCommandedOrientation(builder, tcpCommandedOrientation):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(tcpCommandedOrientation), 0)

def AddTcpCommandedOrientation(builder, tcpCommandedOrientation):
    ArmTelemetryAddTcpCommandedOrientation(builder, tcpCommandedOrientation)

def ArmTelemetryStartTcpCommandedOrientationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpCommandedOrientationVector(builder, numElems):
    return ArmTelemetryStartTcpCommandedOrientationVector(builder, numElems)

def ArmTelemetryAddTcpCommandedLinearVel(builder, tcpCommandedLinearVel):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(tcpCommandedLinearVel), 0)

def AddTcpCommandedLinearVel(builder, tcpCommandedLinearVel):
    ArmTelemetryAddTcpCommandedLinearVel(builder, tcpCommandedLinearVel)

def ArmTelemetryStartTcpCommandedLinearVelVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpCommandedLinearVelVector(builder, numElems):
    return ArmTelemetryStartTcpCommandedLinearVelVector(builder, numElems)

def ArmTelemetryAddTcpCommandedAngularVel(builder, tcpCommandedAngularVel):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(tcpCommandedAngularVel), 0)

def AddTcpCommandedAngularVel(builder, tcpCommandedAngularVel):
    ArmTelemetryAddTcpCommandedAngularVel(builder, tcpCommandedAngularVel)

def ArmTelemetryStartTcpCommandedAngularVelVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTcpCommandedAngularVelVector(builder, numElems):
    return ArmTelemetryStartTcpCommandedAngularVelVector(builder, numElems)

def ArmTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return ArmTelemetryEnd(builder)
