# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Calibration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Calibration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCalibration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Calibration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Calibration
    def CalibrationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def CalibrationStart(builder):
    builder.StartObject(1)

def Start(builder):
    CalibrationStart(builder)

def CalibrationAddCalibrationType(builder, calibrationType):
    builder.PrependInt8Slot(0, calibrationType, 0)

def AddCalibrationType(builder, calibrationType):
    CalibrationAddCalibrationType(builder, calibrationType)

def CalibrationEnd(builder):
    return builder.EndObject()

def End(builder):
    return CalibrationEnd(builder)
