# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClaimControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClaimControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClaimControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClaimControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClaimControl
    def Force(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ClaimControlStart(builder):
    builder.StartObject(1)

def Start(builder):
    ClaimControlStart(builder)

def ClaimControlAddForce(builder, force):
    builder.PrependBoolSlot(0, force, 0)

def AddForce(builder, force):
    ClaimControlAddForce(builder, force)

def ClaimControlEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClaimControlEnd(builder)
