# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

class CommandType(object):
    NONE = 0
    Quickstop = 1
    Calibration = 2
    SingleZeroing = 3
    HumanoidZeroing = 4
    ClearFault = 5
    ClaimControl = 6
    ReleaseControl = 7
    Stop = 8
    SingleSetSpeedOverride = 9
    HumanoidSetSpeedOverride = 10
    SetDriveMode = 11
    CheckUpdate = 12
    ApplyUpdate = 13
    Reboot = 14
    SetStreamingParams = 15
