# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

class CommandResult(object):
    Ok = 0
    InternalError = 10
    NotImplemented = 11
    DecodeFailed = 12
    AlreadyControlled = 13
    NotController = 14
    FaultActive = 15
    QuickstopNotActive = 16
    ModeMismatch = 17
    ZeroingFailed = 18
    ActivityNotIdle = 19
    NotInCspMode = 20
    NotAtZero = 21
    GravityCalibrationRequired = 22
    NotIdleOrAtRest = 23
