# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ControllerEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControllerEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsControllerEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ControllerEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x45\x56", size_prefixed=size_prefixed)

    # ControllerEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControllerEvent
    def HasController(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ControllerEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    ControllerEventStart(builder)

def ControllerEventAddHasController(builder, hasController):
    builder.PrependBoolSlot(0, hasController, 0)

def AddHasController(builder, hasController):
    ControllerEventAddHasController(builder, hasController)

def ControllerEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ControllerEventEnd(builder)
