# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DriveModeEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DriveModeEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDriveModeEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DriveModeEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x45\x56", size_prefixed=size_prefixed)

    # DriveModeEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DriveModeEvent
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def DriveModeEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    DriveModeEventStart(builder)

def DriveModeEventAddMode(builder, mode):
    builder.PrependInt8Slot(0, mode, 0)

def AddMode(builder, mode):
    DriveModeEventAddMode(builder, mode)

def DriveModeEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return DriveModeEventEnd(builder)
