# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

class DriveStatus(object):
    Off = 0
    SettingUp = 1
    BusFault = 2
    DriveFault = 3
    QuickStop = 4
    Operational = 5
