# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DriveStatusEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DriveStatusEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDriveStatusEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DriveStatusEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x45\x56", size_prefixed=size_prefixed)

    # DriveStatusEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DriveStatusEvent
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def DriveStatusEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    DriveStatusEventStart(builder)

def DriveStatusEventAddStatus(builder, status):
    builder.PrependInt8Slot(0, status, 0)

def AddStatus(builder, status):
    DriveStatusEventAddStatus(builder, status)

def DriveStatusEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return DriveStatusEventEnd(builder)
