# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

class EventType(object):
    NONE = 0
    DriveStatusEvent = 1
    MotionStatusEvent = 2
    ActivityEvent = 3
    DriveModeEvent = 4
    ControllerEvent = 5
