# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HumanoidZeroing(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HumanoidZeroing()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHumanoidZeroing(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HumanoidZeroing
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HumanoidZeroing
    def RightJoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # HumanoidZeroing
    def RightJointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # HumanoidZeroing
    def RightJointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HumanoidZeroing
    def RightJointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # HumanoidZeroing
    def LeftJoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # HumanoidZeroing
    def LeftJointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # HumanoidZeroing
    def LeftJointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HumanoidZeroing
    def LeftJointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def HumanoidZeroingStart(builder):
    builder.StartObject(2)

def Start(builder):
    HumanoidZeroingStart(builder)

def HumanoidZeroingAddRightJoints(builder, rightJoints):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rightJoints), 0)

def AddRightJoints(builder, rightJoints):
    HumanoidZeroingAddRightJoints(builder, rightJoints)

def HumanoidZeroingStartRightJointsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRightJointsVector(builder, numElems):
    return HumanoidZeroingStartRightJointsVector(builder, numElems)

def HumanoidZeroingAddLeftJoints(builder, leftJoints):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(leftJoints), 0)

def AddLeftJoints(builder, leftJoints):
    HumanoidZeroingAddLeftJoints(builder, leftJoints)

def HumanoidZeroingStartLeftJointsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartLeftJointsVector(builder, numElems):
    return HumanoidZeroingStartLeftJointsVector(builder, numElems)

def HumanoidZeroingEnd(builder):
    return builder.EndObject()

def End(builder):
    return HumanoidZeroingEnd(builder)
