# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HumanoidTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HumanoidTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHumanoidTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HumanoidTelemetryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # HumanoidTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HumanoidTelemetry
    def Right(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmTelemetry import ArmTelemetry
            obj = ArmTelemetry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HumanoidTelemetry
    def Left(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmTelemetry import ArmTelemetry
            obj = ArmTelemetry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HumanoidTelemetryStart(builder):
    builder.StartObject(2)

def Start(builder):
    HumanoidTelemetryStart(builder)

def HumanoidTelemetryAddRight(builder, right):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(right), 0)

def AddRight(builder, right):
    HumanoidTelemetryAddRight(builder, right)

def HumanoidTelemetryAddLeft(builder, left):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(left), 0)

def AddLeft(builder, left):
    HumanoidTelemetryAddLeft(builder, left)

def HumanoidTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return HumanoidTelemetryEnd(builder)
