# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HumanoidCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HumanoidCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHumanoidCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HumanoidCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # HumanoidCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HumanoidCommand
    def Right(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmCommand import ArmCommand
            obj = ArmCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HumanoidCommand
    def Left(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmCommand import ArmCommand
            obj = ArmCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HumanoidCommandStart(builder):
    builder.StartObject(2)

def Start(builder):
    HumanoidCommandStart(builder)

def HumanoidCommandAddRight(builder, right):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(right), 0)

def AddRight(builder, right):
    HumanoidCommandAddRight(builder, right)

def HumanoidCommandAddLeft(builder, left):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(left), 0)

def AddLeft(builder, left):
    HumanoidCommandAddLeft(builder, left)

def HumanoidCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return HumanoidCommandEnd(builder)
