# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HumanoidSetSpeedOverride(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HumanoidSetSpeedOverride()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHumanoidSetSpeedOverride(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HumanoidSetSpeedOverride
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HumanoidSetSpeedOverride
    def RightVelocityFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # HumanoidSetSpeedOverride
    def RightAccelerationFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # HumanoidSetSpeedOverride
    def LeftVelocityFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # HumanoidSetSpeedOverride
    def LeftAccelerationFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def HumanoidSetSpeedOverrideStart(builder):
    builder.StartObject(4)

def Start(builder):
    HumanoidSetSpeedOverrideStart(builder)

def HumanoidSetSpeedOverrideAddRightVelocityFactor(builder, rightVelocityFactor):
    builder.PrependFloat32Slot(0, rightVelocityFactor, 1.0)

def AddRightVelocityFactor(builder, rightVelocityFactor):
    HumanoidSetSpeedOverrideAddRightVelocityFactor(builder, rightVelocityFactor)

def HumanoidSetSpeedOverrideAddRightAccelerationFactor(builder, rightAccelerationFactor):
    builder.PrependFloat32Slot(1, rightAccelerationFactor, 1.0)

def AddRightAccelerationFactor(builder, rightAccelerationFactor):
    HumanoidSetSpeedOverrideAddRightAccelerationFactor(builder, rightAccelerationFactor)

def HumanoidSetSpeedOverrideAddLeftVelocityFactor(builder, leftVelocityFactor):
    builder.PrependFloat32Slot(2, leftVelocityFactor, 1.0)

def AddLeftVelocityFactor(builder, leftVelocityFactor):
    HumanoidSetSpeedOverrideAddLeftVelocityFactor(builder, leftVelocityFactor)

def HumanoidSetSpeedOverrideAddLeftAccelerationFactor(builder, leftAccelerationFactor):
    builder.PrependFloat32Slot(3, leftAccelerationFactor, 1.0)

def AddLeftAccelerationFactor(builder, leftAccelerationFactor):
    HumanoidSetSpeedOverrideAddLeftAccelerationFactor(builder, leftAccelerationFactor)

def HumanoidSetSpeedOverrideEnd(builder):
    return builder.EndObject()

def End(builder):
    return HumanoidSetSpeedOverrideEnd(builder)
