# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JointImpedance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JointImpedance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJointImpedance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JointImpedanceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # JointImpedance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JointImpedance
    def Stiffness(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointImpedance
    def StiffnessAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointImpedance
    def StiffnessLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointImpedance
    def StiffnessIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # JointImpedance
    def Damping(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointImpedance
    def DampingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointImpedance
    def DampingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointImpedance
    def DampingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def JointImpedanceStart(builder):
    builder.StartObject(2)

def Start(builder):
    JointImpedanceStart(builder)

def JointImpedanceAddStiffness(builder, stiffness):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stiffness), 0)

def AddStiffness(builder, stiffness):
    JointImpedanceAddStiffness(builder, stiffness)

def JointImpedanceStartStiffnessVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStiffnessVector(builder, numElems):
    return JointImpedanceStartStiffnessVector(builder, numElems)

def JointImpedanceAddDamping(builder, damping):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(damping), 0)

def AddDamping(builder, damping):
    JointImpedanceAddDamping(builder, damping)

def JointImpedanceStartDampingVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDampingVector(builder, numElems):
    return JointImpedanceStartDampingVector(builder, numElems)

def JointImpedanceEnd(builder):
    return builder.EndObject()

def End(builder):
    return JointImpedanceEnd(builder)
