# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JointTwistCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JointTwistCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJointTwistCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JointTwistCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # JointTwistCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JointTwistCommand
    def Twist(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointTwistCommand
    def TwistAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointTwistCommand
    def TwistLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointTwistCommand
    def TwistIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # JointTwistCommand
    def ImpedanceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # JointTwistCommand
    def Impedance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def JointTwistCommandStart(builder):
    builder.StartObject(3)

def Start(builder):
    JointTwistCommandStart(builder)

def JointTwistCommandAddTwist(builder, twist):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(twist), 0)

def AddTwist(builder, twist):
    JointTwistCommandAddTwist(builder, twist)

def JointTwistCommandStartTwistVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTwistVector(builder, numElems):
    return JointTwistCommandStartTwistVector(builder, numElems)

def JointTwistCommandAddImpedanceType(builder, impedanceType):
    builder.PrependUint8Slot(1, impedanceType, 0)

def AddImpedanceType(builder, impedanceType):
    JointTwistCommandAddImpedanceType(builder, impedanceType)

def JointTwistCommandAddImpedance(builder, impedance):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(impedance), 0)

def AddImpedance(builder, impedance):
    JointTwistCommandAddImpedance(builder, impedance)

def JointTwistCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return JointTwistCommandEnd(builder)
