# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JointPoseCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JointPoseCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJointPoseCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JointPoseCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # JointPoseCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JointPoseCommand
    def Position(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointPoseCommand
    def PositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointPoseCommand
    def PositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointPoseCommand
    def PositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # JointPoseCommand
    def Velocity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointPoseCommand
    def VelocityAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointPoseCommand
    def VelocityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointPoseCommand
    def VelocityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # JointPoseCommand
    def ImpedanceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # JointPoseCommand
    def Impedance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def JointPoseCommandStart(builder):
    builder.StartObject(4)

def Start(builder):
    JointPoseCommandStart(builder)

def JointPoseCommandAddPosition(builder, position):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    JointPoseCommandAddPosition(builder, position)

def JointPoseCommandStartPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPositionVector(builder, numElems):
    return JointPoseCommandStartPositionVector(builder, numElems)

def JointPoseCommandAddVelocity(builder, velocity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)

def AddVelocity(builder, velocity):
    JointPoseCommandAddVelocity(builder, velocity)

def JointPoseCommandStartVelocityVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVelocityVector(builder, numElems):
    return JointPoseCommandStartVelocityVector(builder, numElems)

def JointPoseCommandAddImpedanceType(builder, impedanceType):
    builder.PrependUint8Slot(2, impedanceType, 0)

def AddImpedanceType(builder, impedanceType):
    JointPoseCommandAddImpedanceType(builder, impedanceType)

def JointPoseCommandAddImpedance(builder, impedance):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(impedance), 0)

def AddImpedance(builder, impedance):
    JointPoseCommandAddImpedance(builder, impedance)

def JointPoseCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return JointPoseCommandEnd(builder)
