# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotionCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MotionCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMotionCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MotionCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # MotionCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotionCommand
    def ProtocolVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # MotionCommand
    def Seq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MotionCommand
    def TtlMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MotionCommand
    def RobotCommandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MotionCommand
    def RobotCommand(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def MotionCommandStart(builder):
    builder.StartObject(5)

def Start(builder):
    MotionCommandStart(builder)

def MotionCommandAddProtocolVersion(builder, protocolVersion):
    builder.PrependUint16Slot(0, protocolVersion, 1)

def AddProtocolVersion(builder, protocolVersion):
    MotionCommandAddProtocolVersion(builder, protocolVersion)

def MotionCommandAddSeq(builder, seq):
    builder.PrependUint64Slot(1, seq, 0)

def AddSeq(builder, seq):
    MotionCommandAddSeq(builder, seq)

def MotionCommandAddTtlMs(builder, ttlMs):
    builder.PrependUint32Slot(2, ttlMs, 0)

def AddTtlMs(builder, ttlMs):
    MotionCommandAddTtlMs(builder, ttlMs)

def MotionCommandAddRobotCommandType(builder, robotCommandType):
    builder.PrependUint8Slot(3, robotCommandType, 0)

def AddRobotCommandType(builder, robotCommandType):
    MotionCommandAddRobotCommandType(builder, robotCommandType)

def MotionCommandAddRobotCommand(builder, robotCommand):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(robotCommand), 0)

def AddRobotCommand(builder, robotCommand):
    MotionCommandAddRobotCommand(builder, robotCommand)

def MotionCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return MotionCommandEnd(builder)
