# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotionStatusEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MotionStatusEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMotionStatusEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MotionStatusEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x45\x56", size_prefixed=size_prefixed)

    # MotionStatusEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotionStatusEvent
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def MotionStatusEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    MotionStatusEventStart(builder)

def MotionStatusEventAddStatus(builder, status):
    builder.PrependInt8Slot(0, status, 0)

def AddStatus(builder, status):
    MotionStatusEventAddStatus(builder, status)

def MotionStatusEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return MotionStatusEventEnd(builder)
