# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Quickstop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Quickstop()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuickstop(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Quickstop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Quickstop
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def QuickstopStart(builder):
    builder.StartObject(1)

def Start(builder):
    QuickstopStart(builder)

def QuickstopAddState(builder, state):
    builder.PrependInt8Slot(0, state, 0)

def AddState(builder, state):
    QuickstopAddState(builder, state)

def QuickstopEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuickstopEnd(builder)
