# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReleaseControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReleaseControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReleaseControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReleaseControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReleaseControlStart(builder):
    builder.StartObject(0)

def Start(builder):
    ReleaseControlStart(builder)

def ReleaseControlEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReleaseControlEnd(builder)
