# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SafetyState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SafetyState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSafetyState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SafetyStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # SafetyState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SafetyState
    def AnyFault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SafetyState
    def AllOpEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SafetyState
    def QuickstopRequested(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SafetyState
    def QuickstopActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SafetyState
    def LastReceivedSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SafetyState
    def HasController(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SafetyStateStart(builder):
    builder.StartObject(6)

def Start(builder):
    SafetyStateStart(builder)

def SafetyStateAddAnyFault(builder, anyFault):
    builder.PrependBoolSlot(0, anyFault, 0)

def AddAnyFault(builder, anyFault):
    SafetyStateAddAnyFault(builder, anyFault)

def SafetyStateAddAllOpEnabled(builder, allOpEnabled):
    builder.PrependBoolSlot(1, allOpEnabled, 0)

def AddAllOpEnabled(builder, allOpEnabled):
    SafetyStateAddAllOpEnabled(builder, allOpEnabled)

def SafetyStateAddQuickstopRequested(builder, quickstopRequested):
    builder.PrependBoolSlot(2, quickstopRequested, 0)

def AddQuickstopRequested(builder, quickstopRequested):
    SafetyStateAddQuickstopRequested(builder, quickstopRequested)

def SafetyStateAddQuickstopActive(builder, quickstopActive):
    builder.PrependBoolSlot(3, quickstopActive, 0)

def AddQuickstopActive(builder, quickstopActive):
    SafetyStateAddQuickstopActive(builder, quickstopActive)

def SafetyStateAddLastReceivedSeq(builder, lastReceivedSeq):
    builder.PrependUint64Slot(4, lastReceivedSeq, 0)

def AddLastReceivedSeq(builder, lastReceivedSeq):
    SafetyStateAddLastReceivedSeq(builder, lastReceivedSeq)

def SafetyStateAddHasController(builder, hasController):
    builder.PrependBoolSlot(5, hasController, 0)

def AddHasController(builder, hasController):
    SafetyStateAddHasController(builder, hasController)

def SafetyStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SafetyStateEnd(builder)
