# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetDriveMode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetDriveMode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetDriveMode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetDriveMode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetDriveMode
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SetDriveModeStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetDriveModeStart(builder)

def SetDriveModeAddMode(builder, mode):
    builder.PrependInt8Slot(0, mode, 0)

def AddMode(builder, mode):
    SetDriveModeAddMode(builder, mode)

def SetDriveModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetDriveModeEnd(builder)
