# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetStreamingParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetStreamingParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetStreamingParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetStreamingParams
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetStreamingParams
    def Kp(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SetStreamingParams
    def KpAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SetStreamingParams
    def KpLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SetStreamingParams
    def KpIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # SetStreamingParams
    def Kd(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SetStreamingParams
    def KdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SetStreamingParams
    def KdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SetStreamingParams
    def KdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SetStreamingParams
    def TLa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetStreamingParamsStart(builder):
    builder.StartObject(3)

def Start(builder):
    SetStreamingParamsStart(builder)

def SetStreamingParamsAddKp(builder, kp):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(kp), 0)

def AddKp(builder, kp):
    SetStreamingParamsAddKp(builder, kp)

def SetStreamingParamsStartKpVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKpVector(builder, numElems):
    return SetStreamingParamsStartKpVector(builder, numElems)

def SetStreamingParamsAddKd(builder, kd):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kd), 0)

def AddKd(builder, kd):
    SetStreamingParamsAddKd(builder, kd)

def SetStreamingParamsStartKdVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKdVector(builder, numElems):
    return SetStreamingParamsStartKdVector(builder, numElems)

def SetStreamingParamsAddTLa(builder, tLa):
    builder.PrependFloat32Slot(2, tLa, 0.0)

def AddTLa(builder, tLa):
    SetStreamingParamsAddTLa(builder, tLa)

def SetStreamingParamsEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetStreamingParamsEnd(builder)
