# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SingleCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # SingleCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleCommand
    def Arm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmCommand import ArmCommand
            obj = ArmCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SingleCommandStart(builder):
    builder.StartObject(1)

def Start(builder):
    SingleCommandStart(builder)

def SingleCommandAddArm(builder, arm):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(arm), 0)

def AddArm(builder, arm):
    SingleCommandAddArm(builder, arm)

def SingleCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleCommandEnd(builder)
