# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleSetSpeedOverride(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleSetSpeedOverride()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleSetSpeedOverride(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleSetSpeedOverride
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleSetSpeedOverride
    def VelocityFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SingleSetSpeedOverride
    def AccelerationFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def SingleSetSpeedOverrideStart(builder):
    builder.StartObject(2)

def Start(builder):
    SingleSetSpeedOverrideStart(builder)

def SingleSetSpeedOverrideAddVelocityFactor(builder, velocityFactor):
    builder.PrependFloat32Slot(0, velocityFactor, 1.0)

def AddVelocityFactor(builder, velocityFactor):
    SingleSetSpeedOverrideAddVelocityFactor(builder, velocityFactor)

def SingleSetSpeedOverrideAddAccelerationFactor(builder, accelerationFactor):
    builder.PrependFloat32Slot(1, accelerationFactor, 1.0)

def AddAccelerationFactor(builder, accelerationFactor):
    SingleSetSpeedOverrideAddAccelerationFactor(builder, accelerationFactor)

def SingleSetSpeedOverrideEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleSetSpeedOverrideEnd(builder)
