# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleZeroing(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleZeroing()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleZeroing(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleZeroing
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleZeroing
    def Joints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SingleZeroing
    def JointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SingleZeroing
    def JointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SingleZeroing
    def JointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SingleZeroingStart(builder):
    builder.StartObject(1)

def Start(builder):
    SingleZeroingStart(builder)

def SingleZeroingAddJoints(builder, joints):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(joints), 0)

def AddJoints(builder, joints):
    SingleZeroingAddJoints(builder, joints)

def SingleZeroingStartJointsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartJointsVector(builder, numElems):
    return SingleZeroingStartJointsVector(builder, numElems)

def SingleZeroingEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleZeroingEnd(builder)
