# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SingleTelemetryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # SingleTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleTelemetry
    def Arm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.ArmTelemetry import ArmTelemetry
            obj = ArmTelemetry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SingleTelemetryStart(builder):
    builder.StartObject(1)

def Start(builder):
    SingleTelemetryStart(builder)

def SingleTelemetryAddArm(builder, arm):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(arm), 0)

def AddArm(builder, arm):
    SingleTelemetryAddArm(builder, arm)

def SingleTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return SingleTelemetryEnd(builder)
