# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StreamCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStreamCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StreamCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StreamCommand
    def ProtocolVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # StreamCommand
    def CommandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # StreamCommand
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def StreamCommandStart(builder):
    builder.StartObject(3)

def Start(builder):
    StreamCommandStart(builder)

def StreamCommandAddProtocolVersion(builder, protocolVersion):
    builder.PrependUint16Slot(0, protocolVersion, 1)

def AddProtocolVersion(builder, protocolVersion):
    StreamCommandAddProtocolVersion(builder, protocolVersion)

def StreamCommandAddCommandType(builder, commandType):
    builder.PrependUint8Slot(1, commandType, 0)

def AddCommandType(builder, commandType):
    StreamCommandAddCommandType(builder, commandType)

def StreamCommandAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder, command):
    StreamCommandAddCommand(builder, command)

def StreamCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return StreamCommandEnd(builder)
