# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StreamCommandResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamCommandResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStreamCommandResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StreamCommandResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StreamCommandResponse
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # StreamCommandResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StreamCommandResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    StreamCommandResponseStart(builder)

def StreamCommandResponseAddResult(builder, result):
    builder.PrependInt8Slot(0, result, 0)

def AddResult(builder, result):
    StreamCommandResponseAddResult(builder, result)

def StreamCommandResponseAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    StreamCommandResponseAddMessage(builder, message)

def StreamCommandResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return StreamCommandResponseEnd(builder)
