# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SystemStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # SystemState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemState
    def DriveStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SystemState
    def Activity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SystemState
    def ActivityStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # SystemState
    def ActivityTotal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # SystemState
    def Motion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SystemState
    def IsImpedance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SystemStateStart(builder):
    builder.StartObject(6)

def Start(builder):
    SystemStateStart(builder)

def SystemStateAddDriveStatus(builder, driveStatus):
    builder.PrependInt8Slot(0, driveStatus, 0)

def AddDriveStatus(builder, driveStatus):
    SystemStateAddDriveStatus(builder, driveStatus)

def SystemStateAddActivity(builder, activity):
    builder.PrependInt8Slot(1, activity, 0)

def AddActivity(builder, activity):
    SystemStateAddActivity(builder, activity)

def SystemStateAddActivityStep(builder, activityStep):
    builder.PrependUint16Slot(2, activityStep, 0)

def AddActivityStep(builder, activityStep):
    SystemStateAddActivityStep(builder, activityStep)

def SystemStateAddActivityTotal(builder, activityTotal):
    builder.PrependUint16Slot(3, activityTotal, 0)

def AddActivityTotal(builder, activityTotal):
    SystemStateAddActivityTotal(builder, activityTotal)

def SystemStateAddMotion(builder, motion):
    builder.PrependInt8Slot(4, motion, 0)

def AddMotion(builder, motion):
    SystemStateAddMotion(builder, motion)

def SystemStateAddIsImpedance(builder, isImpedance):
    builder.PrependBoolSlot(5, isImpedance, 0)

def AddIsImpedance(builder, isImpedance):
    SystemStateAddIsImpedance(builder, isImpedance)

def SystemStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SystemStateEnd(builder)
