# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TcpImpedance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TcpImpedance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTcpImpedance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TcpImpedanceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x43\x4D", size_prefixed=size_prefixed)

    # TcpImpedance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TcpImpedance
    def Stiffness(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TcpImpedance
    def StiffnessAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # TcpImpedance
    def StiffnessLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TcpImpedance
    def StiffnessIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TcpImpedance
    def Damping(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TcpImpedance
    def DampingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # TcpImpedance
    def DampingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TcpImpedance
    def DampingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def TcpImpedanceStart(builder):
    builder.StartObject(2)

def Start(builder):
    TcpImpedanceStart(builder)

def TcpImpedanceAddStiffness(builder, stiffness):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stiffness), 0)

def AddStiffness(builder, stiffness):
    TcpImpedanceAddStiffness(builder, stiffness)

def TcpImpedanceStartStiffnessVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStiffnessVector(builder, numElems):
    return TcpImpedanceStartStiffnessVector(builder, numElems)

def TcpImpedanceAddDamping(builder, damping):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(damping), 0)

def AddDamping(builder, damping):
    TcpImpedanceAddDamping(builder, damping)

def TcpImpedanceStartDampingVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDampingVector(builder, numElems):
    return TcpImpedanceStartDampingVector(builder, numElems)

def TcpImpedanceEnd(builder):
    return builder.EndObject()

def End(builder):
    return TcpImpedanceEnd(builder)
