# automatically generated by the FlatBuffers compiler, do not modify

# namespace: motion

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TelemetryData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemetryData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemetryData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TelemetryDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x54\x45", size_prefixed=size_prefixed)

    # TelemetryData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemetryData
    def ProtocolVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # TelemetryData
    def Seq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TelemetryData
    def Safety(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.SafetyState import SafetyState
            obj = SafetyState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryData
    def RobotType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemetryData
    def Robot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # TelemetryData
    def System(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ruvion.motion.SystemState import SystemState
            obj = SystemState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TelemetryDataStart(builder):
    builder.StartObject(6)

def Start(builder):
    TelemetryDataStart(builder)

def TelemetryDataAddProtocolVersion(builder, protocolVersion):
    builder.PrependUint16Slot(0, protocolVersion, 1)

def AddProtocolVersion(builder, protocolVersion):
    TelemetryDataAddProtocolVersion(builder, protocolVersion)

def TelemetryDataAddSeq(builder, seq):
    builder.PrependUint64Slot(1, seq, 0)

def AddSeq(builder, seq):
    TelemetryDataAddSeq(builder, seq)

def TelemetryDataAddSafety(builder, safety):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(safety), 0)

def AddSafety(builder, safety):
    TelemetryDataAddSafety(builder, safety)

def TelemetryDataAddRobotType(builder, robotType):
    builder.PrependUint8Slot(3, robotType, 0)

def AddRobotType(builder, robotType):
    TelemetryDataAddRobotType(builder, robotType)

def TelemetryDataAddRobot(builder, robot):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(robot), 0)

def AddRobot(builder, robot):
    TelemetryDataAddRobot(builder, robot)

def TelemetryDataAddSystem(builder, system):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(system), 0)

def AddSystem(builder, system):
    TelemetryDataAddSystem(builder, system)

def TelemetryDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemetryDataEnd(builder)
